//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookSubjects
    {
        public long Id { get; set; }
        public string Subject { get; set; }
        public string Book_key { get; set; }
    
        public virtual Books Books { get; set; }
    }
}
