//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerIssue
    {
        public int Cutomer_Id { get; set; }
        public string Book_Id { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public System.DateTime ReturnUntil { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Klient_2 Klient_2 { get; set; }
    }
}
